const Portfolio_data = [
  {
    id: 1,
    project: "Camping Gears",
    totalLike: "600",
    title: "An inventory management full stack web project using reactjs, mongodb, nodejs",
    image: "https://i.ibb.co/mRGtvp7/camping.png",
    description: "This website is created to control a warehouse. In this project, I have used camping idea to implement the entire process. Here, I created a login registration system using jwt access token where any user can try to register/login with email and password securely. This registration system also contain signin with google popup, accept terms, do a password reset etc. It has header, footer, and many components such as Banner, Blogs, Contact, Home, InventoryItems,Speciality, StoreMapLocation etc. I have used react router to create navigation bar, set route, protected route, restrictions etc. In manage inventories, user can add item, manage item, delete item, see my items etc. User can update an inventory stock, restock item, deliver item where quantity decreases etc. For look and style, I used tailwind css framework, tailwind-elements, flowbite, toastify, google fonts, react-hook-form etc",
    project_url: "https://github.com/robinrakibul/camping-gears-react-client",
    live_url: "https://camping-gears-ac126.web.app/",
  },
  {
    id: 2,
    project: "Delta Manufacturer",
    totalLike: "750",
    title: "A car parts manufacturer full stack web project using reactjs, mongodb, nodejs, stripe etc",
    image: "https://i.ibb.co/vh9X8sn/delta.png",
    description: "In this project, I have used manufacturer website idea to implement the entire system.Here, I have created a secured login registration system, google login system using jwt access token where any user can try to register/ login with email and password or join with google securely. It has header, footer, and many pages and ideas such as homepage, tools, banner, review, businessInfo, myPortfolio, blogs, dashboard, contact, purchase page, paymnet system using stripe, seperate admin / user panels, adding product, making admin etcAdmin dashboard has myprofile, update profile, manage all the products, adding a product, managing all the orders, all users, etc all working features.User dashboard has myprofile, update profile, add review, my orders, etc features. I have used react router, query to create navigation bar, set route, protect route, restrictions etc.For look and style, I have used tailwind css framework, daisyui, toastify, google font, react - hook - form, etc.This is a full stack MERN full interactive website.",
    project_url: "https://github.com/robinrakibul/delta-car-parts-manufacturer-react-client",
    live_url: "http://delta-car-parts-manufacturer.web.app/",
  },
  {
    id: 3,
    project: "A Famous Writer",
    totalLike: "300",
    title: "An API based frontend web project with reactjs",
    image: "https://i.ibb.co/WVzkrb9/writer.png",
    description: "I have created a website by a writer named, Muhammed Zafar Iqbal. In this project, I used React, Tailwind CSS, Firebase for authentication, and API for storing website data.",
    project_url: "https://github.com/robinrakibul/zafar-iqbal-writer-react",
    live_url: "https://independent-service-prov-4ddd4.web.app/",
  },
  {
    id: 4,
    project: "Car Repair Services",
    totalLike: "750",
    title: "Car repair services management full stack web project using reactjs, mongodb, nodejs etc",
    image: "https://i.ibb.co/YjKytD7/car.png",
    description: "Main tools used in this project: Node server, React app, Bootstrap5, Firebase etc",
    project_url: "https://github.com/robinrakibul/car-repair-services-react-client",
    live_url: "https://car-repair-services-c9851.web.app/",
  },
  {
    id: 5,
    project: "Expense Tracker System",
    totalLike: "750",
    title: "This expense tracking system php, mysql web project",
    image: "https://i.ibb.co/cLsFMDY/expense.png",
    description: "This project is created using php, mysql. I did this project in my educational institution",
    project_url: "https://github.com/robinrakibul/Expense-Tracker-System-Using-PHP-MySQL",
    live_url: "https://expense-tracker-system-php.000webhostapp.com/",
  }
]
export default Portfolio_data
